### ISSUE TITLE
Warning before recovering ACW encoders

### ISSUE THREAD

**Issue by isotuela** [lsst-ts/ts_tma_tma-documentation_maintenance-documents_bosch-controller_bosch-rexroth-recovery#2]
Hi Julen! 
Can you add a warning in the document here before proceeding with the recovery of ACW encoders?
https://ts-tma.lsst.io/docs/tma_maintenance_bosch-controller_bosch-rexroth-recovery/Bosch-Rexroth-Recovery.html#solving-issue-with-actual-position-value 
Something like "Only proceed if you fully understand the procedure as some of these steps are delicate and could be causing further troubles"
Please and thank you, 
Ioana

**Comment by julen-garcia** [comment]
@isotuela done, please take a look, if this is what you meant i'll mege it to update the doc site

**Comment by isotuela** [comment]
Yes, looks good. Thank you!

**Comment by julen-garcia** [comment]
okay, thanks
